name: Cancel a test round

on: workflow_dispatch

env:
  NODE_VERSION: 16.x

jobs:
  setup-and-tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install g++ library dependencies
      run: |
        sudo apt update
        sudo apt-get install build-essential libgmp-dev libsodium-dev nlohmann-json3-dev nasm g++ curl
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install zkutil
      run: |
        cargo install zkutil --version 0.3.2
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Download batch 64 params
      run: |
        ls -la $GITHUB_WORKSPACE
        $GITHUB_WORKSPACE/.github/scripts/download-batch64-params.sh
    - name: Build CLR
      run: |
        yarn && yarn build
    - name: Start hardhat network
      run: |
        yarn start:node &
    - name: Run script tests
      run: |
        export NODE_CONFIG=$(node -e "const snarkParamsPath=process.env.GITHUB_WORKSPACE + '/params'; console.log(JSON.stringify({ snarkParamsPath }));")
        echo $NODE_CONFIG
        yarn test:local
