name: Deploy to IPFS

on:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x
  IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  IPFS_DEPLOY_CLOUDFLARE__ZONE: yuetloo.xyz
  IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.www.yuetloo.xyz
  IPFS_DEPLOY_INFURA__PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
  IPFS_DEPLOY_INFURA__PROJECT_SECRET: ${{ secrets.INFURA_PROJECT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      cid: ${{ steps.upload.outputs.cid }}
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build
      run: |
        mkdir -p example
        echo "hello world2" > example/hello.txt
    - id: upload
      name: upload folder
      run: |
        npm install -g ipfs-deploy
        # use -C to stop copying to clipboard
        ipfs-deploy -c QmV6GNfjCh6SAayiks7rrAYtSWzadzBhqbpNg52yzhKu6Z -d cloudflare -C
