name: Deploy to IPFS

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Clrfund branch name'
        required: true
        default: 'merge/vue-3'

env:
  NODE_VERSION: 16.x
  IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  IPFS_DEPLOY_CLOUDFLARE__ZONE: yuetloo.xyz
  IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.clrfund.yuetloo.xyz
  IPFS_DEPLOY_INFURA__PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
  IPFS_DEPLOY_INFURA__PROJECT_SECRET: ${{ secrets.INFURA_PROJECT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Checkout CI scripts
      uses: actions/checkout@v3
    - name: Checkout CLR
      uses: actions/checkout@v3
      with:
        repository: clrfund/monorepo
        ref: ${{ github.event.inputs.branch_name }}
        path: monorepo
    - name: Build
      run: |
        cd monorepo
        yarn && yarn build
    - id: upload
      name: upload folder
      run: |
        cd monorepo/vue-app
        # use -C to stop copying to clipboard
        npx ipfs-deploy -p pinata -d cloudflare -C dist
