name: Deploy to IPFS

on:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      cid: ${{ steps.upload.outputs.cid }}
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install IPFS
      run: |
        wget https://dist.ipfs.tech/kubo/v0.18.1/kubo_v0.18.1_linux-amd64.tar.gz
        tar -xvzf kubo_v0.18.1_linux-amd64.tar.gz
        cd kubo
        ./install.sh
        ipfs --version
    - name: Run IPFS daemon
      run: |
        ipfs init
        ipfs daemon &
    - name: Build
      run: |
        mkdir -p example
        echo "hello world" > example/hello.txt
    - id: upload
      name: upload folder
      run: |
        ipfs add --recursive --progress ./example/ | tee add.out
        hash=$(cat add.out | sed -n 's/added \(.*\) example$/\1/p')
        echo "cid=${hash}" >> $GITHUB_OUTPUT
        curl "https://api.pinata.cloud/pinning/pinByHash" \
          -X POST \
          --header 'Authorization: Bearer PINATA JWT' \
          --header 'Content-Type: application/json' \
          -d '{"hashToPin":"{{ outputs.cid }}"'