name: Deploy to IPFS

on:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      cid: ${{ steps.upload.outputs.cid }}
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build
      run: |
        mkdir -p example
        echo "hello world2" > example/hello.txt
    - id: upload
      name: upload folder
      run: |
        npm i -g pinata-upload-cli
        pinata-cli -a ${{ secrets.PINATA_JWT }}
        pinata-cli -u ./example
