name: Finalize mantle testnet 2

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Clrfund branch name'
        required: true
        default: 'cohort/EthSingapore'

env:
  NODE_VERSION: 16.x
  NETWORK: "mantle-testnet"
  COORDINATOR_ETH_PK: ${{ secrets.ARBITRUM_GOERLI_COORDINATOR_WALLET_PRIVATE_KEY }}
  COORDINATOR_PK: ${{ secrets.ARBITRUM_GOERLI_COORDINATOR_MACI_PRIVATE_KEY }}
  FACTORY_ADDRESS: 0x8De1b57be4cE29Eb8d769d2310381F1CAB331007


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Checkout CI scripts
      uses: actions/checkout@v3
    - name: Checkout CLR
      uses: actions/checkout@v3
      with:
        repository: clrfund/monorepo
        ref: ${{ github.event.inputs.branch_name }}
        path: monorepo
    - name: Build
      run: |
        cd monorepo
        yarn && yarn build
    - name: Run finalize scripts
      run: |
        cd monorepo/contracts
        yarn hardhat run --network "${NETWORK}" scripts/finalize.ts
