name: Finalize mantle testnet

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Clrfund branch name'
        required: true
        default: 'cohort/EthSingapore'

env:
  NODE_VERSION: 16.x
  NETWORK: "mantle-testnet"
  COORDINATOR_ETH_PK: ${{ secrets.ARBITRUM_GOERLI_COORDINATOR_WALLET_PRIVATE_KEY }}
  COORDINATOR_PK: ${{ secrets.ARBITRUM_GOERLI_COORDINATOR_MACI_PRIVATE_KEY }}


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install g++ library dependencies
      run: |
        sudo apt update
        sudo apt-get install build-essential libgmp-dev libsodium-dev nlohmann-json3-dev nasm g++ curl
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install zkutil
      run: |
        cargo install zkutil --version 0.3.2
    - name: Checkout CI scripts
      uses: actions/checkout@v3
    - name: Checkout CLR
      uses: actions/checkout@v3
      with:
        repository: clrfund/monorepo
        ref: ${{ github.event.inputs.branch_name }}
        path: monorepo
    - name: Build
      run: |
        cd monorepo
        yarn && yarn build
    - name: Download batch 64 params
      run: |
        ls -la $GITHUB_WORKSPACE
        $GITHUB_WORKSPACE/.github/scripts/download-batch64-params.sh
    - name: Run finalize scripts
      run: |
        export NODE_CONFIG=$(node -e "const snarkParamsPath=process.env.GITHUB_WORKSPACE + '/params'; console.log(JSON.stringify({ snarkParamsPath }));")
        # tally and finalize
        cd monorepo/contracts
        yarn hardhat tally --round-address 0xDf71Ae228545Ee109Ab625730c64Ad1Eb479fC2b --start-block 25314300 --network "${NETWORK}"
        curl --location --request POST 'https://api.pinata.cloud/pinning/pinFileToIPFS' \
          --header "Authorization: Bearer ${{ secrets.PINATA_JWT }}" \
          --form 'file=@"tally.json"'
        yarn hardhat run --network "${NETWORK}" scripts/finalize.ts
