name: Deploy to IPFS

on:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x
  SUBGRPAH_URL: "https://api.thegraph.com/subgraphs/name/yuetloo/clrfund-arbitrum-goerli"
  NETWORK: "arbitrum-goerli"
  COORDINATOR_ETH_PK: ${{ secrets.ARBITRUM_GOERLI_COORDINATOR_WALLET_PRIVATE_KEY }}
  COORDINATOR_PK: ${{ secrets.ARBITRUM_GOERLI_COORDINATOR_MACI_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install g++ library dependencies
      run: |
        sudo apt update
        sudo apt-get install build-essential libgmp-dev libsodium-dev nlohmann-json3-dev nasm g++ curl
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install zkutil
      run: |
        cargo install zkutil --version 0.3.2
    - name: Checkout CLR
      uses: actions/checkout@v3
      with:
        repository: clrfund/monorepo
        ref: fix/circuit-batch-size
        path: monorepo
    - name: Build
      run: |
        cd monorepo
        yarn && yarn build
    - name: Download batch 64 params
      run: |
        ls -la $GITHUB_WORKSPACE
        $GITHUB_WORKSPACE/.github/scripts/download-batch64-params.sh
    - name: Run finalize scripts
      run: |
        export NODE_CONFIG=$(node -e "const snarkParamsPath=process.env.GITHUB_WORKSPACE + '/params'; console.log(JSON.stringify({ snarkParamsPath }));")
        export FACTORY=$(curl -X POST -d '{"query":"{fundingRoundFactories {currentRound {id}}}"}' $SUBGRPAH_URL)
        export FACTORY_ADDRESS=$(node -e 'console.log(JSON.parse(process.env.FACTORY).data.fundingRoundFactories[0].id)')
        export ROUND=$(curl -X POST -d '{"query":"{fundingRoundFactories {id}}"}' $SUBGRPAH_URL)
        export ROUND_ADDRESS=$(node -e 'console.log(JSON.parse(process.env.ROUND).data.fundingRoundFactories[0].currentRound.id)')
        # tally and finalize
        cd contracts
        yarn hardhat run --network "${NETWORK}" scripts/tally.ts
        yarn hardhat run --network "${NETWORK}" scripts/finalize.ts
        curl --location --request POST 'https://api.pinata.cloud/pinning/pinFileToIPFS' \
          --header "Authorization: Bearer ${{ secrets.PINATA_JWT }}" \
          --form 'file=@"tally.json"'
