name: Repo name test

on: 
  workflow_dispatch:

env:
  GITHUB_REPO_NAME:  ${{ github.event.repository.name }}
  VITE_BASE: '/${{ github.event.repository.name }}/'
  GEN_CNAME: 'no'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: echo repo name
      if: env.GEN_CNAME == 'yes'
      run: |
        echo $GITHUB_REPO_NAME
        echo ${{ env.VUE_BASE }}
