name: Manual test

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

env:
  WALLET_PRIVATE_KEY:  ${{ secrets.ARBITRUM_GOERLI_COORDINATOR_WALLET_PRIVATE_KEY }}

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: export key
      run: |
        echo -n "${{ secrets.ARBITRUM_GOERLI_COORDINATOR_WALLET_PRIVATE_KEY }}" | openssl enc -aes-256-cbc -a -salt -pass pass:${{ secrets.SSH_KEY }} -pbkdf2 -iter 100000
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        npm install
    - name: Run test script
      run: |
        echo "Tags: ${{ github.event.inputs.tags }}" 
        yarn hardhat run scripts/get-block-number.js --network arbitrum-goerli
        which scp


