name: Manual test

on: 
  workflow_dispatch:

env:
  GITHUB_REPO_NAME:  ${{ github.event.repository.name }}

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: echo repo name
      run: |
        echo $GITHUB_REPO_NAME
