name: Manual test

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

env:
  WALLET_PRIVATE_KEY:  ${{ secrets.ARBITRUM_GOERLI_COORDINATOR_WALLET_PRIVATE_KEY }}

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: export key
      run: |
        echo "coordingator key" > coordinator.pk
        ls -l coordinator.pk
    - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: '.'
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        npm install
    - name: Run test script
      run: |
        echo "Tags: ${{ github.event.inputs.tags }}" 
        yarn hardhat run scripts/get-block-number.js --network arbitrum-goerli
        which scp


