name: End to end tests

on: pull_request

env:
  NODE_VERSION: 16.x

jobs:
  checkLabels:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.labels.*.name
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        echo pull request has label
        JSON=${{ toJson(github.event.pull_request.labels) }}
        echo "matrix={\"include\":$JSON}" >> $GITHUB_OUTPUT
  build-snarks:
    runs-on: ubuntu-22.04
    needs: [checkLabels]
    strategy:
      matrix: ${{ fromJson(needs.checkLabels.outputs.matrix) }}
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install g++ library dependencies
      run: |
        echo matrix label ${{ matrix.label }}
        sudo apt update
        sudo apt-get install build-essential libgmp-dev libsodium-dev nlohmann-json3-dev nasm g++ curl
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install zkutil
      run: |
        cargo install zkutil --version 0.3.2
    - name: Checkout MACI
      if: ${{ matrix.label }} != 'batch64'
      uses: actions/checkout@v3
      with:
        repository: privacy-scaling-explorations/maci
        ref: v0.10.1
    - name: Checkout CLR
      uses: actions/checkout@v3
      with:
        repository: clrfund/monorepo
        ref: fix/circuit-batch-size
        path: monorepo
    - name: Build MACI
      if:  ${{ matrix.label }} != 'batch64'
      run: |
        git config --global url."https://".insteadOf ssh://
        npm i && npm run bootstrap && npm run build
    - name: Build snarks - small
      if:  ${{ matrix.label }} == 'small'
      run: |
        cd circuits
        ./scripts/buildSnarksSmall.sh
        chmod +x params/batchUstSmall params/qvtSmall
        chmod +r params/*
        params/batchUstSmall
        cp params/BatchUpdateStateTreeVerifierSmall.sol $GITHUB_WORKSPACE/monorepo/contracts/contracts/snarkVerifiers/
        cp params/QuadVoteTallyVerifierSmall.sol $GITHUB_WORKSPACE/monorepo/contracts/contracts/snarkVerifiers/
        ln -s params $GITHUB_WORKSPACE/params
    - name: Download batch 64 params
      if:  ${{ matrix.label }} == 'batch64'
      run: |
        $GITHUB_WORKSPACE/.github/scripts/download-batch64-params.sh
    - name: Build CLR
      run: |
        cd monorepo
        yarn && yarn build
    - name: Start hardhat network
      run: |
        cd monorepo
        yarn start:node &
    - name: Run e2e tests
      run: |
        cd monorepo
        export NODE_CONFIG=$(node -e "const snarkParamsPath=process.env.GITHUB_WORKSPACE + '/params'; console.log(JSON.stringify({ snarkParamsPath }));")
        echo $NODE_CONFIG
        yarn test:e2e
