name: Create Version

on: 
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: major, minor, or patch version
        options:
        - patch
        - minor
        - major

jobs:
  createVersion:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        npm install
    - name: Create new version
      run: |
        echo "Version: ${{ github.event.inputs.version }}" 
        npm version ${{ github.event.inputs.version }}
        git push origin --tags
