name: End to end tests

on:
  push

env:
  NODE_VERSION: 16.x
  CIRCUIT_TYPE: small

jobs:
  build-snarks:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout MACI
      uses: actions/checkout@v3
      with:
        repository: privacy-scaling-explorations/maci
        ref: v0.10.1
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install g++ library dependencies
      run: |
        sudo apt update
        sudo apt-get install build-essential libgmp-dev libsodium-dev nlohmann-json3-dev nasm g++ curl
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install zkutil
      run: |
        cargo install zkutil --version 0.3.2
    - name: Build MACI
      run: |
        git config --global url."https://".insteadOf ssh://
        npm i && npm run bootstrap && npm run build
    - name: Build snarks
      run: |
        cd circuits
        ./scripts/buildSnarksSmall.sh
        chmod +x params/batchUstSmall params/qvtSmall
        chmod +r params/*
        params/batchUstSmall
        curl https://raw.githubusercontent.com/yuetloo/ci-test/main/1668381255361.input.json -o input.json
        params/batchUstSmall ./1668381255361.input.json output.json
    - name: Checkout CLR
      uses: actions/checkout@v3
      with:
        repository: clrfund/monorepo
        ref: fix/circuit-batch-size
        path: monorepo
    - name: Install and run tests
      run: |
        cd monorepo
        yarn && yarn build
        yarn start:node &
        cp ../maci/params/BatchUpdateStateTreeVerifierSmall.sol contracts/contracts/snarkVerifiers/
        cp ../maci/params/QuadVoteTallyVerifierSmall.sol contracts/contracts/snarkVerifiers/
        export NODE_CONFIG=$(node -e "const snarkParamsPath=process.env.GITHUB_WORKSPACE + '/params'; console.log(JSON.stringify({ snarkParamsPath }));")
        echo $NODE_CONFIG
        yarn test:e2e
